### ISSUE TITLE
average 0.25 is too high

### ISSUE THREAD

**Issue by tommyhlw** [qedsoftware/brukeropusreader#2]
https://github.com/qedsoftware/brukeropusreader/blob/999779cb9c24ca65040101ed49c8d4316752c1a0/brukeropusreader/opus_reader.py#L37

missed some spectra because of this. 
`ab=not_ig`

instead of 
```
    for x in not_ig:
        if np.average(spc[x]) > 0.25:
            ab.append(x)
```
worked for me

**Comment by tdyczek** [comment]
Please try the latest version of the package, the files you posted should be openable now.
