### ISSUE TITLE
Switch license to LGPL

### ISSUE THREAD

**Issue by mlazowik** [qedsoftware/brukeropusreader#25]
This is a proposal to switch from GNU AGPL v3.0 to GNU LGPL v3.0.

The motivation is to make this code more reuse friendly, while enforcing that any improvements made to it are accessible to the open source community. In particular the library is used in @spectrochempy, which as of today is using the `CeCILL-B` license that is not compatible with AGPL.

All external (the ones that were not commiting as part of their work for QED.ai) contributors present in the latest version need to agree to this change. Please indicate agreement or disagreement with a comment below if you are one of the authors.

Contributors as of 77287d24d0a75d94cb95e0e36f0c8072d4785984:
- [x] QED.ai, represented by @willywutang 
- [x] @fernandezc
- [ ] @thanakijwanavit – no show, but the only commit is 3 lines in documentation, does not seem copyrightable https://github.com/qedsoftware/brukeropusreader/pull/6/files
- [x] @tommyhlw 
- [x] @htherrien 
- [x] @atravert

**Comment by atravert** [comment]
I agree

**Comment by fernandezc** [comment]
I agree

**Comment by tommyhlw** [comment]
I agree

**Comment by willywutang** [comment]
I agree
--
William Wu, Ph.D.
*QED.ai* | https://qed.ai
