### ISSUE TITLE
Fixed requirements in setup.py prevent installation

### ISSUE THREAD

**Issue by typorian** [qedsoftware/brukeropusreader#4]
The hard requirements being spelled out with == instead of >= seem to prevent the installation of the package, I fixed it by changing the two requirements of numpy and scipy.

**Comment by willywutang** [comment]
Thanks we will work on this. May I ask what you are using the package for? Please write to us at: brukeropusreader@qed.ai

**Comment by typorian** [comment]
Unfortunately I think I will not be able to use it, as it seems I can only extract the first present spectrum from a chromatography mode file (which is the reference single channel) and not all of the measurements that are present.

**Comment by willywutang** [comment]
Please write to us by e-mail, we would like to discuss your needs further to see if we can work out something and understand all the details. There are certain design decisions we made for our use case  but we could potentially adjust the design for other use cases. The requirements have been adjusted as per your request.
