### ISSUE TITLE
Can't open background files

### ISSUE THREAD

**Issue by MrAnimaniac** [qedsoftware/brukeropusreader#5]
I can't open background files like this one. As I'm quite new to programming in general, I don't know how to fix this... yet. 

[2019-02.28_HG0.zip](https://github.com/qedsoftware/brukeropusreader/files/3139910/2019-02.28_HG0.zip)

--------------------------edit------------------------------
Some further information to the issue: My reference measurement files (or background files) do not contain an absorption or transmission spectrum. Only the reference spectrum is present. 

It looks as if this is somehow  connected to line 142:
	`end_diff = npy – end_spc`
returning -184. As far as I have tested, this value is always the same for reference measurements. 
Line 135 raises therefor an error, as only positive values are regarded. 

I found an R-file also designed to open OPUS files. Here you can find something perhaps related: https://github.com/philipp-baumann/simplerspec/blob/master/R/read-opus-universal.R (line 144 following)
But I know to little to see if this is anyhow relevant.

**Comment by willywutang** [comment]
Please try the latest version of the package, the files you posted should be openable now.
